admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'
urlpatterns = [
    path('submissions/', views.submissions, name='submissions'),
    path('all/', views.all, name='all'),
    path('accept/?id=<int:pk>/', views.accept, name='accept'),
    path('reject/?id=<int:pk>/', views.reject, name='reject'),
    path('delete/?id=<int:pk>/', views.delete, name='delete'),
]

project_show/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('', include('projects.urls', namespace='projects')),
    path('', include('admin_app.urls', namespace='admin_app')),
    path('', include('search_app.urls', namespace='search_app')),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('submit/', views.submit, name='submit'),
    path('track/', views.track, name='track'),
    path('lists/', views.lists, name='lists'),
    path('details/?id=<int:pk>/', views.details, name='details'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    # path('projects/', views.projects, name='projects'),
    path('guide/', views.guide, name='guide'),
    path('contact/', views.contact, name='contact'),
]

admin_app/models.py
from django.db import models

# Create your models here.

admin_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from projects.models import Project
from modules.file_upload import UploadFile

# done
def submissions(request):
    if not request.user.is_staff:
        return redirect('user:index')

    context = {
        'projects': Project.objects.filter(status='processing').order_by('-created'),
    }
    return render(request, 'submission.html', context=context)

# done
def all(request):
    if not request.user.is_staff:
        return redirect('user:index')

    context = {
        'projects': Project.objects.all().order_by('-created'),
    }
    return render(request, 'all.html', context=context)

# done
def accept(request, pk):
    if not request.user.is_staff:
        return redirect('user:index')

    if request.is_ajax():
        project_obj = Project.objects.get(pk=pk)
        project_obj.status = 'accepted'
        project_obj.save()
        return JsonResponse({
            'status': True,
            'msg': 'Successfully Updated Data.',
            'url': '/submissions/',
        })

# done
def reject(request, pk):
    if not request.user.is_staff:
        return redirect('user:index')

    if request.is_ajax():
        project_obj = Project.objects.get(pk=pk)
        project_obj.status = 'rejected'
        project_obj.save()

        upload_obj = UploadFile(request)
        upload_obj.delete(firebase_url=project_obj.firebase_url)

        return JsonResponse({
            'status': True,
            'msg': 'Successfully Updated Data.',
            'url': '/submissions/',
        })

# done
def delete(request, pk):
    if not request.user.is_staff:
        return redirect('user:index')

    if request.is_ajax():
        project_obj = Project.objects.get(pk=pk)

        upload_obj = UploadFile(request)
        upload_obj.delete(firebase_url=project_obj.firebase_url)

        project_obj.delete()

        return JsonResponse({
            'status': True,
            'msg': 'Successfully Updated Data.',
            'url': '/all/',
        })

admin_app/templates/all.html
{% extends 'admin_base.html' %}

{% block title %}
<title>All Submissions</title>
{% endblock %}

{% block style %}
<style>
    .download:hover {
        text-decoration: none;
    }
</style>
{% endblock %}

{% block content %}
<div class="col-md-7 text-justify">
    {% if projects.count == 0 %}
    <div class="alert alert-warning d-flex flex-row justify-content-center">
        Did you submit any&nbsp;<strong>Awesome Project</strong>?
    </div>
    {% else %}
    <table class="table">
        <tr>
            <th>Add Time</th>
            <th>Project Title</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for project in projects %}
        <tr>
            <td>{{ project.last_updated }}</td>
            <td>
                <a href="" class="text-primary download" onclick="details(event)" url="{% url 'projects:details' project.pk %}" data-toggle="modal" data-target="#container-modal">
                    {{ project.project_name|title }}
                </a>
            </td>
            <td>
                {% if project.status == 'processing' %}
                <span class="text-warning">{{ project.status|title }}</span>
                {% elif project.status == 'accepted' %}
                <span class="text-success">{{ project.status|title }}</span>
                {% else %}
                <span class="text-danger">{{ project.status|title }}</span>
                {% endif %}
            </td>
            <td>
                <button class="btn btn-outline-danger ml-2" onclick="do_action(event)" url="{% url 'admin_app:delete' project.pk %}">
                    <span class="" role="status" aria-hidden="true"></span>
                    Delete
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>

 <!-- container modal -->
<div class="modal fade" id="container-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <!-- <h4 class="modal-title">Seller Registration</h4> -->
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="dynamic-load">

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
function details(event){
    event.preventDefault();
    $('#dynamic-load').html('')
    $('#dynamic-load').load(
        event.target.attributes.url.value
    )
}
</script>
{% endblock %}

admin_app/templates/submission.html
{% extends 'admin_base.html' %}

{% block title %}
<title>Submissions</title>
{% endblock %}

{% block style %}
<style>
    .download:hover {
        text-decoration: none;
    }
</style>
{% endblock %}

{% block content %}
<div class="col-md-7 text-justify">
    {% if projects.count == 0 %}
    <div class="alert alert-warning d-flex flex-row justify-content-center">
        Did you submit any&nbsp;<strong>Awesome Project</strong>?
    </div>
    {% else %}
    <table class="table">
        <tr>
            <th>Add Time</th>
            <th>Project Title</th>
            <th>Actions</th>
            
        </tr>
        {% for project in projects %}
        <tr>
            <td>{{ project.last_updated }}</td>
            <td>
                <a href="" class="text-primary download" onclick="details(event)" url="{% url 'projects:details' project.pk %}" data-toggle="modal" data-target="#container-modal">
                    {{ project.project_name|title }}
                </a>
            </td>
            <td>
                <button class="btn btn-outline-success" onclick="do_action(event)" url="{% url 'admin_app:accept' project.pk %}">
                    <span class="" role="status" aria-hidden="true"></span>
                    Accept
                </button>
                <button class="btn btn-outline-danger ml-2" onclick="do_action(event)" url="{% url 'admin_app:reject' project.pk %}">
                    <span class="" role="status" aria-hidden="true"></span>
                    Reject
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>

 <!-- container modal -->
<div class="modal fade" id="container-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <!-- <h4 class="modal-title">Seller Registration</h4> -->
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="dynamic-load">

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
function details(event){
    event.preventDefault();
    $('#dynamic-load').html('')
    $('#dynamic-load').load(
        event.target.attributes.url.value
    )
}
</script>
{% endblock %}