admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'
urlpatterns = [
    path('submissions/', views.submissions, name='submissions'),
    path('all/', views.all, name='all'),
    path('accept/?id=<int:pk>/', views.accept, name='accept'),
    path('reject/?id=<int:pk>/', views.reject, name='reject'),
    path('delete/?id=<int:pk>/', views.delete, name='delete'),
]

project_show/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('', include('projects.urls', namespace='projects')),
    path('', include('admin_app.urls', namespace='admin_app')),
    path('', include('search_app.urls', namespace='search_app')),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('submit/', views.submit, name='submit'),
    path('track/', views.track, name='track'),
    path('lists/', views.lists, name='lists'),
    path('details/?id=<int:pk>/', views.details, name='details'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    # path('projects/', views.projects, name='projects'),
    path('guide/', views.guide, name='guide'),
    path('contact/', views.contact, name='contact'),
]

templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet"
        href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
        integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous"/>
    {% block title %}
    {% endblock %}

    <style>
        @-webkit-keyframes spinner-grow {
            0% {
                -webkit-transform: scale(0);
                transform: scale(0);
            }
    
            50% {
                opacity: 1;
            }
        }
    
        @keyframes spinner-grow {
            0% {
                -webkit-transform: scale(0);
                transform: scale(0);
            }
    
            50% {
                opacity: 1;
            }
        }
    
        .spinner-grow {
            display: inline-block;
            width: 2rem;
            height: 2rem;
            vertical-align: text-bottom;
            background-color: currentColor;
            border-radius: 50%;
            opacity: 0;
            -webkit-animation: spinner-grow .75s linear infinite;
            animation: spinner-grow .75s linear infinite;
        }
    
        .spinner-grow-sm {
            width: 1rem;
            height: 1rem;
        }
    </style>
    {% block style %}
    {% endblock %}
</head>

<body class="bg-light">
    <!-- header -->
    <div class="container-fluid" id="header">
        <div id="hamburger" class="d-none">
            <i class="fas fa-bars"></i>
        </div>
        <div class="row">
            <div class="col-md-9 d-flex">
                <img src="/static/images/bulb-icon.png" alt="" class="" style="height: 95px; width: 95px; padding: 5px;" />
                <div class="text-left text-white pl-2">
                    <a href="{% url 'user:index' %}" id="title">Project Showcase</a>
                    <i class="d-block">
                    A Place Where You Can Share Your Projects
                    </i>
                </div>
            </div>

            <div class="col-md-3 text-md-right text-center text-white py-2">
                <div class="float-md-right mx-md-">
                    {% if not user.is_authenticated %}
                    <a href="" class="btn btn-outline-light mr-2" data-toggle="modal" data-target="#login-modal">Login</a>
                    <a href="" class="btn btn-outline-light" data-toggle="modal" data-target="#reg-modal">Register</a>
                    {% else %}
                    <a href="{% url 'user:logout' %}" class="btn btn-outline-light">Logout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid pt-4 px-md-0 p-4"> 
        <div class="row">
            <!-- navigation -->
            <div class="col-md-2" id="nav">
                <ul>
                    <li><a href="{% url 'admin_app:submissions' %}">Submissions</a></li>
                    <li><a href="{% url 'admin_app:all' %}">All Projects</a></li>
                </ul>
            </div>
            
            <!-- body text -->
            {% block content %}
            {% endblock %}
            
            <!-- reght tab  -->
            <div class="col-md-3 bg-ad">
                <div class="pr-2">

                    <img src="/static/images/open_access.png" class="img-fluid mt-3">

                    <img src="/static/images/cross_ref.png" class="img-fluid mt-3">
                </div>
            </div>
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="/static/js/app.js"></script>
    <script src="/static/js/alerting.js"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
        integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
        crossorigin="anonymous"></script>
    <script>$(document).ready(function () { $('body').bootstrapMaterialDesign(); });</script>

    <script>
    function do_action(event){
        event.preventDefault();
        $(event.target.firstElementChild).addClass('spinner-grow spinner-grow-sm');
        $.ajax({
            type: 'post',
            url: event.target.attributes.url.value,
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (data) {
                $(event.target.firstElementChild).removeClass('spinner-grow spinner-grow-sm')
                if (data.status == true) {
                    success_alert(data.msg);

                    window.setTimeout(function () {
                    window.location.href = data.url;
                    }, 1500);
                }
                else {
                    $(event.target.firstElementChild).removeClass('spinner-grow spinner-grow-sm')
                    error_alert(data.msg);
                }
            },
        });
    }
    </script>

    {% block script %}
    {% endblock %}
</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet"
            href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
            integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
        <link rel="stylesheet" href="/static/css/style.css"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous"/>
        {% block title %}
        {% endblock %}

        {% block style %}
        {% endblock %}
    </head>

    <body class="bg-light">
        <!-- header -->
        <div class="container-fluid" id="header">
            <div id="hamburger" class="d-none">
                <i class="fas fa-bars"></i>
            </div>
            <div class="row">
                <div class="col-md-9 d-flex">
                    <img src="/static/images/bulb-icon.png" alt="" class="" style="height: 95px; width: 95px; padding: 5px;" />
                    <div class="text-left text-white pl-2">
                        <a href="{% url 'user:index' %}" id="title">Project Showcase</a>
                        <i class="d-block">
                        A Place Where You Can Share Your Projects
                        </i>
                    </div>
                </div>

                <div class="col-md-3 text-md-right text-center text-white py-2">
                    <div class="float-md-right mx-md-">
                        {% if not user.is_authenticated %}
                        <a href="" class="btn btn-outline-light mr-2" data-toggle="modal" data-target="#login-modal">Login</a>
                        <a href="" class="btn btn-outline-light" data-toggle="modal" data-target="#reg-modal">Register</a>
                        {% else %}
                        <a href="{% url 'user:logout' %}" class="btn btn-outline-light">Logout</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid pt-4 px-md-0 p-4"> 
            <div class="row">
                <!-- navigation -->
                <div class="col-md-2" id="nav">
                    <ul>
                        <li><a href="{% url 'user:index' %}">Home</a></li>
                        <li><a href="{% url 'projects:lists' %}"> View Projects </a></li>
                        <li><a href="{% url 'user:guide' %}">Guide for Authors</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'projects:submit' %}">Submit Your Project</a></li>
                        <li><a href="{% url 'projects:track' %}">Track Your Project</a></li>
                        {% endif %}
                        <li><a href="{% url 'user:contact' %}">Contact</a></li>
                    </ul>
                </div>
                
                <!-- body text -->
                {% block content %}
                {% endblock %}
                
                <!-- reght tab  -->
                <div class="col-md-3 bg-ad">
                    <div class="pr-2">
                        <!-- <div class="card bg-primary d-block mt-3">
                            <div class="card-header">
                                <h4 class="text-light">Announcement</h4>
                            </div>
                            <div class="card-body bg-light">
                                <span class="d-block">
                                Dear Veterinarians and researchers, you are invited to submit
                                your valuable research works/findings in Bangladesh Veterinary
                                Journal. Please <a href="#">click here </a> to
                                submit your paper.
                                </span>
                            </div>
                        </div> -->

                        <img src="/static/images/open_access.png" class="img-fluid mt-3">

                        <img src="/static/images/cross_ref.png" class="img-fluid mt-3">
                    </div>
                </div>
            </div>
        </div>
        <!-- body  -->

        <!-- login modal -->
        <div class="modal fade" id="login-modal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Log In</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <form action="{% url 'user:login' %}" onsubmit="submit_form(event)">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email" class="bmd-label-floating">Email</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label for="password" class="bmd-label-floating">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <input type="submit" class="btn btn-outline-success" value="Log In">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- reg buyer modal -->
        <div class="modal fade" id="reg-modal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Registration</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <form action="{% url 'user:register' %}" onsubmit="submit_form(event)">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="first_name" class="bmd-label-floating">First Name</label>
                                <input type="text" class="form-control" id="first_name" name="first_name" required>
                            </div>
                            <div class="form-group">
                                <label for="last_name" class="bmd-label-floating">Last Name</label>
                                <input type="text" class="form-control" id="last_name" name="last_name" required>
                            </div>
                            <div class="form-group">
                                <label for="institute" class="bmd-label-floating">Institute</label>
                                <input type="text" class="form-control" id="institute" name="institute" required>
                            </div>
                            <div class="form-group">
                                <label for="id_no" class="bmd-label-floating">Id</label>
                                <input type="text" class="form-control" id="id_no" name="id_no" required>
                            </div>
                            <div class="form-group">
                                <label for="session" class="bmd-label-floating">Id</label>
                                <input type="text" class="form-control" id="session" name="session" required>
                            </div>
                            <div class="form-group">
                                <label for="email" class="bmd-label-floating">Email</label>
                                <input type="email" class="form-control" id="email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label for="phone" class="bmd-label-floating">Phone</label>
                                <input type="tel" class="form-control" id="phone" name="phone" required>
                            </div>
                            <div class="form-group">
                                <label for="address" class="bmd-label-floating">Address</label>
                                <input type="text" class="form-control" id="address" name="address" required>
                            </div>
                            <div class="form-group">
                                <label for="password" class="bmd-label-floating">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="form-group">
                                <label for="confirm" class="bmd-label-floating">Confirm Password</label>
                                <input type="password" class="form-control" id="confirm" name="confirm" required>
                            </div>
                            <input type="submit" class="btn btn-outline-success" value="Register">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="/static/js/app.js"></script>
        <script src="/static/js/alerting.js"></script>
        <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"
            integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9"
            crossorigin="anonymous"></script>
        <script>$(document).ready(function () { $('body').bootstrapMaterialDesign(); });</script>

        <script>
        function logout() {
            window.location.href = "{% url 'user:logout' %}";
        }

        function submit_form(event) {
            event.preventDefault();
            var form = event.target;
            var url = form.action;
            var formData = new FormData(form);

            $.ajax({
                type: 'post',
                url: url,
                data: formData,
                success: function (data) {
                    if (data.status == true) {
                        $('.close').click();
                        success_alert(data.msg);

                        window.setTimeout(function () {
                        window.location.href = data.url;
                        }, 1500);
                    }
                    else {
                        error_alert(data.msg);
                    }
                },
                cache: false,
                contentType: false,
                processData: false,
            });
        }
        </script>

        {% block script %}
        {% endblock %}
    </body>
</html>